PSQLADM-92 : Allow proxysql-admin to use encrypted password
Issue
proxysql-admin uses credentials that are stored in clear text.

Solution
Utilize the MySQL login-path facilities to store obfuscated credentials.

diff --git a/proxysql-status b/proxysql-status
--- a/proxysql-status
+++ b/proxysql-status
@@ -18,6 +18,9 @@ Usage example:
                               (note: this is a case-sensitive match)
     --with-stats-reset      : display _reset tables, by default _reset tables
                               will not be queried.
+    --login-path=<path_name> : use this login-path when querying MySQL
+                              This will override all other credentials supplied.
+    --login-path-file-=<file> : use the login-path stored in this file
 
   The default is to display all tables and files.
 
@@ -34,6 +37,7 @@ EOF
 #   PASSWORD
 #   HOST
 #   PORT
+#   LOGIN_PATH
 #
 # Arguments:
 #   1: arguments to be passed to mysql
@@ -44,9 +48,16 @@ function mysql_exec() {
   local query=$2
   local retvalue
   local retoutput
-  retoutput=$(printf "[client]\nuser=${USER}\npassword=\"${PASSWORD}\"\nhost=${HOST}\nport=${PORT}"  \
-      | mysql --defaults-file=/dev/stdin --protocol=tcp \
-            ${args} -e "${query}")
+
+  if [[ -n $LOGIN_PATH ]]; then
+      retoutput=$(mysql --login-path="$LOGIN_PATH" --protocol=tcp \
+                ${args} -e "${query}")
+  else
+      retoutput=$(printf "[client]\nuser=${USER}\npassword=\"${PASSWORD}\"\nhost=${HOST}\nport=${PORT}"  \
+          | mysql --defaults-file=/dev/stdin --protocol=tcp \
+                ${args} -e "${query}")
+  fi
+
   retvalue=$?
   if [[ -n $retoutput ]]; then
     retoutput+="\n"
@@ -68,15 +79,17 @@ declare DUMP_MONITOR=0
 declare DUMP_FILES=0
 declare TABLE_FILTER=""
 declare DUMP_STATS_RESET_TABLE=0
-
+declare LOGIN_PATH=""
+declare LOGIN_PATH_FILE=""
 
 function parse_args() {
     local go_out=""
+    local positional_args=""
 
    # TODO: kennt, what happens if we don't have a functional getopt()?
     # Check if we have a functional getopt(1)
     if ! getopt --test; then
-        go_out="$(getopt --options=h --longoptions=runtime,main,stats,monitor,files,table:,with-stats-reset,help \
+        go_out="$(getopt --options=h --longoptions=runtime,main,stats,monitor,files,table:,with-stats-reset,login-path:,login-path-file:,help \
         --name="$(basename "$0")" -- "$@")"
         if [[ $? -ne 0 ]]; then
             # no place to send output
@@ -86,10 +99,14 @@ function parse_args() {
         eval set -- "$go_out"
     fi
 
-    for arg
+    while [[ $# -gt 0 ]];
     do
+        arg="$1"
         case "$arg" in
-            -- ) shift; break;;
+            -- )
+                shift
+                positional_args="$@"
+                break;;
             --runtime )
                 shift
                 RUNTIME_OPTION=" LIKE 'runtime_%'"
@@ -124,37 +141,75 @@ function parse_args() {
                 shift
                 DUMP_STATS_RESET_TABLE=1
                 ;;
+            --login-path )
+                LOGIN_PATH="$2"
+                shift 2
+                ;;
+            --login-path-file )
+                LOGIN_PATH_FILE="$2"
+                if [[ ! -e $LOGIN_PATH_FILE ]]; then
+                    echo "ERROR: cannot find login-path-file: $LOGIN_PATH_FILE"
+                    exit 1
+                fi
+                shift 2
+                ;;
             -h | --help )
                 usage
                 exit 1
-                break;;
+                ;;
         esac
     done
 
-    if [[ $# -eq 0 ]]; then
-        if [[ ! -r /etc/proxysql-admin.cnf ]]; then
-            echo "Cannot find /etc/proxysql-admin.cnf."
+    # Reset the args
+    eval set -- "$positional_args"
+
+    if [[ -n $LOGIN_PATH_FILE ]]; then
+        export MYSQL_TEST_LOGIN_FILE="$LOGIN_PATH_FILE"
+    fi
+
+    if [[ -z $LOGIN_PATH ]]; then
+        if [[ $# -eq 0 ]]; then
+            if [[ ! -r /etc/proxysql-admin.cnf ]]; then
+                echo "ERROR: Cannot find /etc/proxysql-admin.cnf."
+                exit 1
+            fi
+            source /etc/proxysql-admin.cnf
+            LOGIN_PATH=${PROXYSQL_LOGIN_PATH-}
+            if [[ -z $LOGIN_PATH ]]; then
+                USER=${PROXYSQL_USERNAME-}
+                PASSWORD=${PROXYSQL_PASSWORD-}
+                HOST=${PROXYSQL_HOSTNAME-}
+                PORT=${PROXYSQL_PORT-}
+            fi
+        elif [[ $# -eq 4 ]]; then
+            USER=$1
+            PASSWORD=$2
+            HOST=$3
+            PORT=$4
+        else
+            echo -e "ERROR: Incorrect usage\n"
+            usage
             exit 1
         fi
-        source /etc/proxysql-admin.cnf
-        USER=$PROXYSQL_USERNAME
-        PASSWORD=$PROXYSQL_PASSWORD
-        HOST=$PROXYSQL_HOSTNAME
-        PORT=$PROXYSQL_PORT
-    elif [[ $# -eq 4 ]]; then
-        USER=$1
-        PASSWORD=$2
-        HOST=$3
-        PORT=$4
-    else
-        echo -e "ERROR: Incorrect usage\n"
-        usage
+    fi
+
+    if [[ -n $LOGIN_PATH_FILE && -z $LOGIN_PATH ]]; then
+        echo "Error: must specify a login-path when using login-path-file"
         exit 1
+    fi
+    if [[ -n $LOGIN_PATH ]]; then
+        echo "Using login-path:$LOGIN_PATH from file:${LOGIN_PATH_FILE:-(default)}"
     fi
 }
 
 
 parse_args "$@"
+
+# Run a test to see if we can connect
+TABLES=$(mysql_exec -BN "SELECT 1" >/dev/null)
+if [[ $? -ne 0 ]]; then
+    exit 1
+fi
 
 if [[ $DUMP_ALL -eq 1 || $DUMP_MAIN -eq 1 ]]; then
     echo "............ DUMPING MAIN DATABASE ............"
